#!/bin/bash
# ──────────────────────────────────────────────────────────────────────────────
#  Smart Auto-Shutdown · Single-File Installer
#  !! AUTO-GENERATED by build.sh — do not edit install.sh directly !!
#
#  Installs an idle-aware auto-shutdown system for Linux servers.
#  After a configurable uptime, the system checks periodically for SSH
#  sessions and CPU usage. If the machine stays idle long enough it
#  shuts itself down automatically.
#
#  One-liner install:
#    curl -fsSL https://raw.githubusercontent.com/oglcn/smart-auto-shutdown/main/install.sh -o /tmp/install-sas.sh && sudo bash /tmp/install-sas.sh
#
#  With defaults (non-interactive):
#    curl -fsSL https://raw.githubusercontent.com/oglcn/smart-auto-shutdown/main/install.sh -o /tmp/install-sas.sh && sudo bash /tmp/install-sas.sh --defaults
#
#  Local usage:
#    sudo ./install.sh                     # interactive
#    sudo ./install.sh --defaults          # accept all defaults
#    sudo ./install.sh --uninstall         # remove everything
#
#  Requirements: systemd, bash >= 4, ss, top
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Paths ────────────────────────────────────────────────────────────────────
INSTALL_DIR="/usr/local/bin"
SYSTEMD_DIR="/etc/systemd/system"
CONFIG_FILE="/etc/smart-auto-shutdown.conf"
STATE_FILE="/var/run/smart-shutdown-state"

# ── Defaults ─────────────────────────────────────────────────────────────────
DEF_BOOT_DELAY="8h"
DEF_CHECK_INTERVAL="10min"
DEF_IDLE_THRESHOLD=3600      # 1 hour in seconds
DEF_CPU_THRESHOLD=20         # percent
DEF_SHUTDOWN_DELAY=1         # minutes warning before halt

# ── Colours & Helpers ────────────────────────────────────────────────────────
if [ -t 1 ]; then
    C_GREEN='\033[0;32m'
    C_RED='\033[0;31m'
    C_YELLOW='\033[1;33m'
    C_CYAN='\033[0;36m'
    C_BOLD='\033[1m'
    C_DIM='\033[2m'
    C_RESET='\033[0m'
else
    C_GREEN='' C_RED='' C_YELLOW='' C_CYAN='' C_BOLD='' C_DIM='' C_RESET=''
fi

banner() {
    echo ""
    echo -e "${C_BOLD}${C_CYAN}"
    echo "  ┌──────────────────────────────────────────┐"
    echo "  │       Smart Auto-Shutdown Installer      │"
    echo "  └──────────────────────────────────────────┘"
    echo -e "${C_RESET}"
}

info()  { echo -e "  ${C_CYAN}→${C_RESET} $*"; }
ok()    { echo -e "  ${C_GREEN}✓${C_RESET} $*"; }
warn()  { echo -e "  ${C_YELLOW}!${C_RESET} $*"; }
fail()  { echo -e "  ${C_RED}✗${C_RESET} $*"; exit 1; }
step()  { echo ""; echo -e "  ${C_BOLD}$*${C_RESET}"; }

# ── Root check ───────────────────────────────────────────────────────────────
require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        fail "This installer must be run as root (use sudo)."
    fi
}

# ── Uninstall ────────────────────────────────────────────────────────────────
do_uninstall() {
    banner
    step "Uninstalling Smart Auto-Shutdown"

    systemctl stop autoshutdown.timer 2>/dev/null || true
    systemctl disable autoshutdown.timer 2>/dev/null || true
    ok "Stopped and disabled timer"

    rm -f "${SYSTEMD_DIR}/autoshutdown.timer" \
          "${SYSTEMD_DIR}/autoshutdown.service"
    systemctl daemon-reload
    ok "Removed systemd units"

    rm -f "${INSTALL_DIR}/smart-shutdown-check.sh" \
          "${INSTALL_DIR}/shutdown-status" \
          "${INSTALL_DIR}/shutdown-control"
    ok "Removed scripts from ${INSTALL_DIR}"

    rm -f "$STATE_FILE"
    ok "Removed runtime state"

    if [ -f "$CONFIG_FILE" ]; then
        warn "Config file kept: ${CONFIG_FILE}"
        warn "Remove manually if no longer needed."
    fi

    echo ""
    ok "Uninstall complete."
    echo ""
    exit 0
}

# ── Pre-flight checks ───────────────────────────────────────────────────────
preflight() {
    step "Checking requirements"

    command -v systemctl >/dev/null 2>&1 || fail "systemd is required but not found."
    ok "systemd"

    command -v ss >/dev/null 2>&1 || fail "'ss' (iproute2) is required but not found."
    ok "ss (iproute2)"

    command -v top >/dev/null 2>&1 || fail "'top' (procps) is required but not found."
    ok "top (procps)"

    local bash_major="${BASH_VERSINFO[0]}"
    [ "$bash_major" -ge 4 ] || fail "bash >= 4 required (found ${BASH_VERSION})."
    ok "bash ${BASH_VERSION}"
}

# ── Validators ───────────────────────────────────────────────────────────────
validate_timespan() {
    [[ "$1" =~ ^[0-9]+(s|sec|min|h|hr|d)?$ ]] || \
    [[ "$1" =~ ^([0-9]+(s|sec|min|h|hr|d))+$ ]]
}

validate_int() {
    [[ "$1" =~ ^[0-9]+$ ]] && [ "$1" -gt 0 ]
}

validate_percent() {
    [[ "$1" =~ ^[0-9]+$ ]] && [ "$1" -gt 0 ] && [ "$1" -le 100 ]
}

# ── Prompt helper (with default + validation) ────────────────────────────────
ask() {
    local var="$1" prompt="$2" default="$3" validator="$4" hint="$5"
    if [ "${USE_DEFAULTS:-}" = "1" ]; then
        eval "$var=\"$default\""
        return
    fi
    while true; do
        read -rp "$(echo -e "  ${C_CYAN}?${C_RESET} ${prompt} ${C_DIM}[${default}]${C_RESET}: ")" input
        input="${input:-$default}"
        if $validator "$input"; then
            eval "$var=\"$input\""
            return
        fi
        echo -e "  ${C_RED}✗${C_RESET} Invalid input. ${hint}"
    done
}

# ── Configure ────────────────────────────────────────────────────────────────
configure() {
    step "Configuration"
    info "Press Enter to accept the default value shown in brackets."
    echo ""

    ask BOOT_DELAY      "Uptime before monitoring starts"             "$DEF_BOOT_DELAY"    \
        validate_timespan "Use systemd time format: e.g. 30min, 2h, 1h30min"

    ask CHECK_INTERVAL  "Check interval once monitoring starts"       "$DEF_CHECK_INTERVAL" \
        validate_timespan "Use systemd time format: e.g. 5min, 10min, 1h"

    ask IDLE_THRESHOLD  "Idle time before shutdown (seconds)"         "$DEF_IDLE_THRESHOLD" \
        validate_int      "Must be a positive integer (seconds). e.g. 1800, 3600"

    ask CPU_THRESHOLD   "CPU % below which system is idle (1-100)"   "$DEF_CPU_THRESHOLD"  \
        validate_percent  "Must be an integer between 1 and 100"

    ask SHUTDOWN_DELAY  "Warning time before halt (minutes)"         "$DEF_SHUTDOWN_DELAY"  \
        validate_int      "Must be a positive integer (minutes). e.g. 1, 5"

    echo ""
    info "Summary:"
    echo -e "    Boot delay      : ${C_GREEN}${BOOT_DELAY}${C_RESET}"
    echo -e "    Check interval  : ${C_GREEN}${CHECK_INTERVAL}${C_RESET}"
    echo -e "    Idle threshold  : ${C_GREEN}$((IDLE_THRESHOLD / 60)) min${C_RESET} (${IDLE_THRESHOLD}s)"
    echo -e "    CPU threshold   : ${C_GREEN}${CPU_THRESHOLD}%${C_RESET}"
    echo -e "    Shutdown delay  : ${C_GREEN}${SHUTDOWN_DELAY} min${C_RESET}"

    if [ "${USE_DEFAULTS:-}" != "1" ]; then
        echo ""
        read -rp "$(echo -e "  ${C_CYAN}?${C_RESET} Proceed with installation? ${C_DIM}[Y/n]${C_RESET}: ")" confirm
        case "${confirm,,}" in
            n|no) echo ""; info "Cancelled."; exit 0 ;;
        esac
    fi
}

# ── Install config file ─────────────────────────────────────────────────────
install_config() {
    step "Writing configuration"

    cat > "$CONFIG_FILE" <<CONF
# Smart Auto-Shutdown Configuration
# Modify these values and restart the timer:
#   sudo systemctl restart autoshutdown.timer

# Seconds of continuous idle (no SSH + low CPU) before shutdown
IDLE_THRESHOLD=${IDLE_THRESHOLD}

# CPU usage percent; below this the system is considered idle
CPU_THRESHOLD=${CPU_THRESHOLD}

# Minutes of warning broadcast before actual halt
SHUTDOWN_DELAY=${SHUTDOWN_DELAY}

# These two are stored in the systemd timer unit:
#   Boot delay     : ${BOOT_DELAY}
#   Check interval : ${CHECK_INTERVAL}
CONF

    ok "Config written to ${CONFIG_FILE}"
}

# ── Install scripts (embedded) ───────────────────────────────────────────────
install_scripts() {
    step "Installing scripts"

    cat > "${INSTALL_DIR}/smart-shutdown-check.sh" <<'SCRIPT_CHECK'
#!/bin/bash
# Smart Auto-Shutdown Check Script
# Checks for SSH sessions and system idle status.
# Only shuts down after sustained idle period with no SSH connections.

set -euo pipefail

CONFIG_FILE="/etc/smart-auto-shutdown.conf"
STATE_FILE="/var/run/smart-shutdown-state"

# Defaults (overridden by config file)
IDLE_THRESHOLD=3600   # seconds of continuous idle before shutdown
CPU_THRESHOLD=20      # percent CPU; below this is "idle"
SHUTDOWN_DELAY=1      # minutes of warning before actual halt

# Load config
if [ -f "$CONFIG_FILE" ]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
fi

check_ssh_sessions() {
    local count
    count=$(ss -tn state established sport = :22 | tail -n +2 | wc -l)
    [ "$count" -eq 0 ]
}

check_system_idle() {
    local cpu_usage cpu_int
    cpu_usage=$(top -bn2 -d 0.5 | grep "Cpu(s)" | tail -1 | awk '{print $2}' | cut -d'%' -f1)
    cpu_int=${cpu_usage%.*}
    [ "$cpu_int" -lt "$CPU_THRESHOLD" ]
}

logger -t smart-shutdown "Running smart shutdown check (idle_threshold=${IDLE_THRESHOLD}s, cpu_threshold=${CPU_THRESHOLD}%)"

if check_ssh_sessions && check_system_idle; then
    if [ -f "$STATE_FILE" ]; then
        IDLE_START=$(cat "$STATE_FILE")
        CURRENT_TIME=$(date +%s)
        IDLE_DURATION=$((CURRENT_TIME - IDLE_START))

        logger -t smart-shutdown "System idle for ${IDLE_DURATION}s (need ${IDLE_THRESHOLD}s)"

        if [ "$IDLE_DURATION" -ge "$IDLE_THRESHOLD" ]; then
            logger -t smart-shutdown "Idle threshold reached. Shutting down system."
            rm -f "$STATE_FILE"
            /sbin/shutdown -h +"$SHUTDOWN_DELAY" \
                "System idle for $((IDLE_THRESHOLD / 60)) min with no SSH. Shutting down in ${SHUTDOWN_DELAY} min."
        fi
    else
        date +%s > "$STATE_FILE"
        logger -t smart-shutdown "Started tracking idle state"
    fi
else
    if [ -f "$STATE_FILE" ]; then
        logger -t smart-shutdown "Activity detected or SSH session active. Resetting idle counter."
        rm -f "$STATE_FILE"
    fi
fi
SCRIPT_CHECK
    chmod 755 "${INSTALL_DIR}/smart-shutdown-check.sh"
    ok "smart-shutdown-check.sh → ${INSTALL_DIR}/"

    cat > "${INSTALL_DIR}/shutdown-status" <<'SCRIPT_STATUS'
#!/bin/bash
# Smart Auto-Shutdown Status Utility

CONFIG_FILE="/etc/smart-auto-shutdown.conf"
STATE_FILE="/var/run/smart-shutdown-state"

IDLE_THRESHOLD=3600
CPU_THRESHOLD=20
BOOT_DELAY="8h"
CHECK_INTERVAL="10min"

if [ -f "$CONFIG_FILE" ]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
fi

C_GREEN='\033[0;32m'
C_RED='\033[0;31m'
C_YELLOW='\033[1;33m'
C_CYAN='\033[0;36m'
C_BOLD='\033[1m'
C_RESET='\033[0m'

echo ""
echo -e "${C_BOLD}╔══════════════════════════════════════╗${C_RESET}"
echo -e "${C_BOLD}║    Smart Auto-Shutdown Status        ║${C_RESET}"
echo -e "${C_BOLD}╚══════════════════════════════════════╝${C_RESET}"
echo ""

if systemctl is-active --quiet autoshutdown.timer 2>/dev/null; then
    echo -e "  Monitoring : ${C_GREEN}● ACTIVE${C_RESET}"
    NEXT=$(systemctl list-timers autoshutdown.timer --no-pager 2>/dev/null | grep autoshutdown | awk '{print $1, $2, $3}')
    [ -n "$NEXT" ] && echo -e "  Next check : ${C_CYAN}${NEXT}${C_RESET}"
else
    echo -e "  Monitoring : ${C_RED}● INACTIVE${C_RESET}"
fi

echo -e "  Uptime     : $(uptime -p)"
echo ""

SSH_COUNT=$(ss -tn state established sport = :22 2>/dev/null | tail -n +2 | wc -l)
CPU_USAGE=$(top -bn2 -d 0.5 2>/dev/null | grep "Cpu(s)" | tail -1 | awk '{print $2}')

echo -e "${C_BOLD}  System State${C_RESET}"
echo -e "  SSH conns  : ${SSH_COUNT}"
echo -e "  CPU usage  : ${CPU_USAGE:-N/A}"
echo ""

if [ -f "$STATE_FILE" ]; then
    IDLE_START=$(cat "$STATE_FILE")
    CURRENT_TIME=$(date +%s)
    IDLE_DURATION=$((CURRENT_TIME - IDLE_START))
    REMAINING=$((IDLE_THRESHOLD - IDLE_DURATION))
    IDLE_MIN=$((IDLE_DURATION / 60))
    REMAINING_MIN=$((REMAINING / 60))

    echo -e "  ${C_YELLOW}⚠  IDLE COUNTDOWN IN PROGRESS${C_RESET}"
    echo -e "  Idle for     : ${IDLE_MIN} min"
    echo -e "  Shutdown in  : ${REMAINING_MIN} min"
else
    echo -e "  ${C_GREEN}✓  No shutdown pending${C_RESET}"
fi

echo ""
echo -e "${C_BOLD}  Configuration${C_RESET}"
echo -e "  Boot delay       : ${BOOT_DELAY}"
echo -e "  Check interval   : ${CHECK_INTERVAL}"
echo -e "  Idle threshold   : $((IDLE_THRESHOLD / 60)) min"
echo -e "  CPU threshold    : ${CPU_THRESHOLD}%"
echo ""
SCRIPT_STATUS
    chmod 755 "${INSTALL_DIR}/shutdown-status"
    ok "shutdown-status → ${INSTALL_DIR}/"

    cat > "${INSTALL_DIR}/shutdown-control" <<'SCRIPT_CONTROL'
#!/bin/bash
# Smart Auto-Shutdown Control Utility

STATE_FILE="/var/run/smart-shutdown-state"

C_GREEN='\033[0;32m'
C_YELLOW='\033[1;33m'
C_BOLD='\033[1m'
C_RESET='\033[0m'

case "${1:-}" in
    pause)
        sudo systemctl stop autoshutdown.timer
        sudo rm -f "$STATE_FILE"
        echo -e "${C_GREEN}✓${C_RESET} Auto-shutdown monitoring ${C_YELLOW}PAUSED${C_RESET}"
        echo "  Run 'shutdown-control resume' to re-enable"
        ;;
    resume)
        sudo systemctl start autoshutdown.timer
        sudo rm -f "$STATE_FILE"
        echo -e "${C_GREEN}✓${C_RESET} Auto-shutdown monitoring ${C_GREEN}RESUMED${C_RESET}"
        echo "  Idle counter has been reset"
        ;;
    reset)
        sudo rm -f "$STATE_FILE"
        echo -e "${C_GREEN}✓${C_RESET} Idle countdown ${C_GREEN}RESET${C_RESET}"
        echo "  Counter will start fresh on next check"
        ;;
    status)
        shutdown-status
        ;;
    logs)
        echo -e "${C_BOLD}=== Recent Auto-Shutdown Logs ===${C_RESET}"
        echo ""
        sudo journalctl -t smart-shutdown -n 30 --no-pager
        ;;
    *)
        echo ""
        echo -e "${C_BOLD}Smart Auto-Shutdown Control${C_RESET}"
        echo ""
        echo "Usage: shutdown-control <command>"
        echo ""
        echo "Commands:"
        echo "  status   Show current auto-shutdown status"
        echo "  pause    Temporarily disable auto-shutdown"
        echo "  resume   Re-enable auto-shutdown monitoring"
        echo "  reset    Reset idle countdown timer"
        echo "  logs     View recent auto-shutdown log entries"
        echo ""
        echo "Examples:"
        echo "  shutdown-control pause    # Disable before a long job"
        echo "  shutdown-control resume   # Re-enable after job completes"
        echo "  shutdown-control status   # Check current status"
        echo ""
        exit 1
        ;;
esac
SCRIPT_CONTROL
    chmod 755 "${INSTALL_DIR}/shutdown-control"
    ok "shutdown-control → ${INSTALL_DIR}/"
}

# ── Install systemd units (embedded) ─────────────────────────────────────────
install_systemd() {
    step "Installing systemd units"

    cat > "${SYSTEMD_DIR}/autoshutdown.timer" <<UNIT_TIMER
[Unit]
Description=Smart auto-shutdown monitor timer

[Timer]
OnBootSec=${BOOT_DELAY}
OnUnitActiveSec=${CHECK_INTERVAL}
Unit=autoshutdown.service

[Install]
WantedBy=timers.target
UNIT_TIMER
    ok "autoshutdown.timer → ${SYSTEMD_DIR}/"

    cat > "${SYSTEMD_DIR}/autoshutdown.service" <<'UNIT_SERVICE'
[Unit]
Description=Smart auto-shutdown check service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/smart-shutdown-check.sh
UNIT_SERVICE
    ok "autoshutdown.service → ${SYSTEMD_DIR}/"

    systemctl daemon-reload
    ok "systemd daemon reloaded"

    systemctl enable autoshutdown.timer
    systemctl start  autoshutdown.timer
    ok "Timer enabled and started"
}

# ── Done ─────────────────────────────────────────────────────────────────────
finish() {
    echo ""
    echo -e "${C_BOLD}${C_GREEN}"
    echo "  ┌──────────────────────────────────────────┐"
    echo "  │         Installation complete!            │"
    echo "  └──────────────────────────────────────────┘"
    echo -e "${C_RESET}"
    echo "  Quick reference:"
    echo ""
    echo -e "    ${C_BOLD}shutdown-control status${C_RESET}   Show current status"
    echo -e "    ${C_BOLD}shutdown-control pause${C_RESET}    Pause monitoring"
    echo -e "    ${C_BOLD}shutdown-control resume${C_RESET}   Resume monitoring"
    echo -e "    ${C_BOLD}shutdown-control logs${C_RESET}     View recent log entries"
    echo ""
    echo -e "  Config: ${C_DIM}${CONFIG_FILE}${C_RESET}"
    echo ""
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
    case "${1:-}" in
        --uninstall|-u)
            require_root
            do_uninstall
            ;;
        --defaults|-y)
            USE_DEFAULTS=1
            ;;
        --help|-h)
            echo "Usage: sudo ./install.sh [--defaults|--uninstall|--help]"
            echo ""
            echo "One-liner install:"
            echo "  curl -fsSL <raw-url>/install.sh | sudo bash"
            echo "  curl -fsSL <raw-url>/install.sh | sudo bash -s -- --defaults"
            exit 0
            ;;
    esac

    require_root
    banner
    preflight
    configure
    install_config
    install_scripts
    install_systemd
    finish
}

main "$@"
